### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by HallowCheshire** [SirHamburger/ShrineOfEmpoweredDio#1]
The new update, Anniversary, has caused the Shrine Of Empowered Dio mod to not only stop working, but cause the shrine of the woods to also stop working. The Shrine of Empowered Dio does not have an option to buy a new dio and the shrine of the woods now consumes money without outputting a healing field.

**Comment by SirHamburger** [comment]
Thanks for the message.
I'll deprecate it until I've time to fix it.

**Comment by SirHamburger** [comment]
Should be fixed now.
